# omicsTL - Transfer Learning Example

<div>
<img src="images/tl_arch1.png" width="500" style="background-color: white;"/>
</div>

This notebook demonstrates the use of omicsTL to create a transfer learning model for synthetic data generated using real data objects.

We will start by loading the required functions.

In [1]:
import warnings
warnings.filterwarnings("always")

from omicstl.simulation_utils.data_generation import response_function, generate_synth_data

The first step is to generate two synthetic data frames. We will be using two different viral datasets with aligned features as the real data sources for the simulated data. The first will represent the source data that we are training the "base" model on, and the second will represent the target data.

For this example we will create two pairs of synthetic data frames, one with a continuous response and one with a categorical response.

In [2]:
import pandas as pd
import numpy as np

source_real_data_path = "data/source_data_real.csv"
target_real_data_path = "data/target_data_real.csv"

source_real_data = pd.read_csv(source_real_data_path, index_col=0)
target_real_data = pd.read_csv(target_real_data_path, index_col=0)

# Non-trivial continuous response function
response_fn = response_function("tanh(df[, 2]) + df[, 1] * df[, ncol(df)] ^ 2")

num_features = 100
num_samples_source = 100
num_samples_target = 50
samples_target_test = 25
samples_target_ensemble = 5

In [3]:
# Continuous response

source_synth_data_cont, _, _ = generate_synth_data(
    data = source_real_data, # input data
    num_features = num_features, # number of output features
    num_samples = num_samples_source, # number of output samples
    response_fn = response_fn, # response function
    snr = 1 # signal to noise ratio
)

target_synth_data_cont, _, _ = generate_synth_data(
    data = target_real_data, # input data
    num_features = num_features, # number of output features
    num_samples = num_samples_target + samples_target_test + samples_target_ensemble, # number of output samples
    response_fn = response_fn, # response function
    snr = 1 # signal to noise ratio
)

display(source_synth_data_cont)
display(target_synth_data_cont)

,0,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,100
0,0.709745,5.169284,-0.801270,-2.481015,0.971358,-2.788133,0.344792,1.319404,-0.229033,0.081958,...,2.221755,0.362435,3.732676,8.089617,3.531047,0.764803,2.611196,1.246202,0.757259,-0.580157
1,-1.182419,5.284342,-1.212539,-2.450351,0.112518,-2.789658,-0.000746,1.257714,-0.020188,0.398173,...,2.329076,0.181900,3.557077,7.937169,3.963873,0.560995,3.143621,0.459065,0.474184,0.468246
2,-0.228918,4.907341,-0.414235,-2.101820,0.583732,-2.926481,-0.648327,1.244020,0.199479,-0.141364,...,1.995018,0.327048,3.774364,7.887075,3.569852,0.890454,3.122125,1.602968,0.943994,0.155247
3,1.070476,5.107220,-0.817031,-2.198386,0.625852,-2.690079,0.150866,1.598720,-0.374176,0.291748,...,1.757760,-0.269355,3.792042,7.879154,3.561271,0.804493,2.588445,1.728053,0.672215,0.121342
4,1.651615,5.420199,-0.525324,-2.415237,1.005190,-2.703323,0.359519,1.376945,0.328053,0.001085,...,2.392239,0.484386,3.667260,7.707040,3.810620,0.830379,2.577513,2.124940,0.033020,-0.599305
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,-1.366329,4.648824,-1.115133,-1.694486,0.818466,-2.517248,-0.381121,1.196717,-0.147013,-0.087889,...,2.135680,0.390318,3.562221,8.027991,4.026159,0.860800,2.668003,1.384969,0.098826,-0.000922
96,1.656332,4.908522,-0.665053,-2.556943,1.114199,-2.873339,-0.223156,1.090769,-0.148751,0.020906,...,1.808230,0.116378,3.532256,7.836456,2.997895,0.751951,3.036141,1.811638,0.358069,-0.718323
97,-1.369651,5.272862,-0.964620,-2.454992,0.439067,-2.718708,0.121382,1.243454,-0.450078,0.218211,...,1.881787,0.284764,3.402504,8.196195,3.283347,0.932596,1.937744,2.838580,0.227059,0.012674
98,-2.335436,4.873174,-0.603693,-2.588740,1.455388,-2.742686,-0.014913,1.362023,-0.303832,-0.016839,...,2.390619,0.499916,3.473040,7.711473,3.276284,0.588535,2.456534,2.181392,0.322333,-0.209638
99,0.638601,5.480088,-0.768131,-2.411605,0.637302,-2.594091,0.353499,1.747251,0.414295,0.074325,...,2.144975,0.486810,3.653917,7.674099,3.764090,1.033709,2.854474,2.115283,0.480203,0.379499

,0,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,100
0,-0.858714,-1.192076,-1.843203,0.425764,-1.928103,-1.706470,-1.907344,-0.806375,0.495380,1.682625,...,-2.556583,-3.999983,3.021161,-1.491902,0.324629,0.579581,5.232790,-0.732302,1.987773,0.182961
1,-1.645498,-1.512046,-2.776914,0.203048,-2.334490,-0.628611,-1.698098,-0.291700,0.348396,1.779148,...,-2.455964,-3.637511,3.189133,-1.108604,0.240107,0.865531,5.464467,-1.311782,2.233184,0.187684
2,-1.271160,-1.505261,-1.766538,0.226851,-2.228543,-1.929425,-1.747420,-0.874122,-0.169380,1.810226,...,-2.647056,-3.873737,3.043445,-2.108507,0.325211,0.569156,5.088865,-0.901268,2.300370,0.468906
3,-0.809590,-2.067170,-2.092256,0.616910,-1.157147,-2.378855,-2.055474,-0.459659,0.218658,1.716537,...,-2.220061,-4.111322,2.946146,-2.630426,0.371037,0.862062,5.085696,-0.843187,1.523889,-0.044226
4,-0.849828,-1.472328,-2.587047,0.889882,-2.803023,-2.060670,-2.031925,-0.535059,-0.239085,2.047370,...,-2.291321,-3.718342,2.865583,-2.399674,0.382917,1.173630,4.889107,-1.197509,3.521448,0.433665
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,-1.697780,-2.395958,-2.248412,-0.660183,-2.038939,-1.708342,-2.055360,-1.592534,0.134013,1.994029,...,-2.371866,-3.617409,3.010403,-1.831470,0.381820,1.280596,4.928786,-1.350042,2.632904,0.277015
76,-1.785944,-1.871045,-2.701426,1.123326,-2.336776,-1.613714,-1.992757,-0.685850,0.389006,1.699597,...,-2.340122,-3.588028,2.845644,-1.893834,0.478603,0.960739,5.312729,-0.808141,2.371492,0.095164
77,-2.363927,-1.785866,-2.459270,0.576606,-2.458442,-0.826019,-1.967408,-0.447435,0.440372,1.143935,...,-2.427535,-3.831840,2.952946,-2.144902,0.192362,0.732021,5.091913,-1.148301,1.466302,-0.043536
78,-0.996614,-1.090444,-2.231536,0.246113,-2.088365,-2.217954,-2.030591,-1.158286,0.147960,1.839563,...,-2.278157,-3.537164,3.366052,-2.380252,0.332666,0.752533,5.321324,-1.130233,0.531972,0.187986
79,-0.888477,-2.837271,-2.104644,0.501004,-2.083480,-2.145835,-2.238674,-0.893656,0.626155,2.215670,...,-2.320195,-4.016915,3.014101,-2.292362,0.010647,2.114517,4.899264,-1.236225,2.042150,-0.236377

In [4]:
# Categorical response

source_synth_data_cat, _, _ = generate_synth_data(
    data = source_real_data, # input data
    num_features = num_features, # number of output features
    num_samples = num_samples_source + samples_target_ensemble, # number of output samples
    response_fn = response_fn, # response function
    snr = 1, # signal to noise ratio
    response_parameters={
        "ncats": 3,
        "quantile": "quantile"
    }
)

target_synth_data_cat, _, _ = generate_synth_data(
    data = target_real_data, # input data
    num_features = num_features, # number of output features
    num_samples = num_samples_target + samples_target_test + samples_target_ensemble, # number of output samples
    response_fn = response_fn, # response function
    snr = 1 ,# signal to noise ratio
    response_parameters={
        "ncats": 3,
        "quantile": "quantile"
    }
)

display(source_synth_data_cat)
display(target_synth_data_cat)

,0,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,100
0,2.0,-1.310469,5.570844,3.700625,-0.619772,0.074271,-0.052646,2.823216,-1.799269,-1.579035,...,4.819066,2.040486,1.986293,5.142695,2.295965,1.155776,4.512663,1.416116,-0.030854,-0.822960
1,1.0,-1.082107,5.268589,3.426564,-0.592814,0.350732,-0.351167,2.793405,-2.393324,-2.054333,...,4.621089,1.925801,2.339705,4.911947,1.461830,0.858679,4.565820,-0.260662,0.451128,-1.013903
2,2.0,-0.737008,4.890618,3.495831,-0.810039,0.442562,0.252116,3.102539,-2.453232,-1.890366,...,4.806363,2.068896,2.118783,5.155596,1.162680,1.053035,4.109277,0.480822,-0.241338,-1.097282
3,3.0,-0.819201,5.091639,3.335201,-0.370575,0.516678,0.110038,2.570169,-2.343234,-1.892962,...,4.399806,2.357678,1.840806,5.226303,1.465903,0.937009,4.079520,0.539711,0.158438,-1.081640
4,2.0,-0.763279,5.557201,3.330069,-0.635902,0.447687,-0.312029,2.790430,-2.356448,-2.818449,...,4.869561,2.199476,2.026253,5.023058,1.372399,1.235917,3.950441,1.128289,0.020330,-1.223108
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,2.0,-0.809713,4.917303,3.364738,-0.882983,0.035671,0.254065,2.800092,-2.212543,-1.895990,...,4.616638,2.356582,1.966760,4.541395,1.447753,0.797124,4.966511,1.640023,0.123759,-0.969684
101,1.0,-1.024245,5.097656,3.526080,-0.764799,0.614209,0.268911,2.683918,-1.644659,-1.821519,...,4.894150,2.121815,1.740149,5.060649,1.266335,0.937450,4.609844,0.894055,0.065500,-1.151515
102,3.0,-1.347499,5.217781,3.363037,-0.596614,1.114721,0.148757,2.703218,-2.633046,-1.557009,...,4.903644,2.212217,2.525541,4.960240,1.529156,0.882572,4.154050,0.454436,0.470143,-0.949239
103,1.0,-1.096823,5.758413,3.526562,-0.592390,0.658155,-0.082963,2.911165,-2.557210,-2.153025,...,4.867976,2.417201,1.925608,5.263617,1.555666,1.300913,4.239458,1.716188,-0.174082,-1.232906
104,2.0,-1.050452,5.227704,3.572933,-0.507850,0.785874,-0.163091,2.841950,-2.353404,-1.734339,...,4.448237,2.318687,2.739278,5.465868,1.597587,1.558405,4.900981,0.372170,-0.393087,-1.121588

,0,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,100
0,3.0,4.769045,2.543019,0.127175,0.915306,-1.533501,-1.506954,-2.092641,4.831195,-0.895564,...,0.457183,0.697152,0.985471,1.314532,3.874959,3.954645,-3.308962,1.215349,0.258778,0.909181
1,3.0,5.018501,2.510326,-0.354174,0.836314,-1.441408,-1.279166,-1.952684,5.115174,-1.016085,...,1.324583,0.500394,-0.396992,1.542943,4.067113,3.846578,-3.243592,1.389933,0.547100,0.846260
2,3.0,4.777021,2.444106,-0.211616,1.276217,-1.884173,-0.344954,-2.020747,4.534157,-0.914388,...,0.544318,0.374025,-0.882429,1.180283,3.777334,3.706993,-3.269312,1.164933,-0.458075,0.917365
3,2.0,4.670300,2.133287,0.160373,1.018033,-1.668420,-0.655789,-1.918660,3.901115,-0.751446,...,0.682099,0.728456,-1.550653,1.217963,4.566282,3.768361,-3.272327,1.315975,0.305532,0.686334
4,1.0,4.175020,2.321022,0.232931,1.254426,-1.740281,-0.941282,-3.815338,4.018373,-1.745579,...,1.240334,-0.032016,-1.387028,1.636593,4.332934,3.911513,-3.142013,1.607726,0.055178,0.651507
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,2.0,4.501208,2.509107,0.109379,1.711110,-1.612816,-1.401761,-1.423005,4.660238,-1.100626,...,0.516574,0.951326,-0.208152,1.669521,4.252707,3.810440,-3.237650,0.915388,0.450955,0.818702
76,2.0,4.159895,2.595269,-0.506128,1.452436,-1.739688,-0.565483,-2.124122,4.580203,-1.332073,...,0.415372,-0.087372,-1.714914,1.437499,3.435024,3.916532,-3.204420,2.143436,0.346091,0.781715
77,1.0,4.551205,2.288389,-0.851173,1.616766,-1.835022,-1.072017,-1.560335,4.247898,-0.711451,...,0.107727,0.438576,-1.295839,1.480109,4.274559,3.632350,-3.172828,1.194807,0.006112,0.566536
78,3.0,3.860609,2.431069,-0.359509,1.211128,-1.751888,-1.669110,-1.111645,4.870790,-1.192881,...,0.035782,1.325843,-0.384502,1.516608,4.106231,3.820769,-3.155858,0.919099,0.523355,0.861473
79,3.0,4.569016,2.406346,-0.419975,0.701233,-1.851113,-1.111626,-3.385429,4.554030,-1.060488,...,0.197951,0.430888,-2.771304,1.160451,4.058868,3.833038,-3.126279,1.183269,0.798316,0.856264

In [5]:
# Set response column name

source_synth_data_cont.rename(columns={source_synth_data_cont.columns[0]: 'response'}, inplace=True)
target_synth_data_cont.rename(columns={target_synth_data_cont.columns[0]: 'response'}, inplace=True)
display(source_synth_data_cont)
display(target_synth_data_cont)

source_synth_data_cat.rename(columns={source_synth_data_cat.columns[0]: 'response'}, inplace=True)
target_synth_data_cat.rename(columns={target_synth_data_cat.columns[0]: 'response'}, inplace=True)
source_synth_data_cat = source_synth_data_cat.astype({"response": np.int64})
target_synth_data_cat = target_synth_data_cat.astype({"response": np.int64})
display(source_synth_data_cat)
display(target_synth_data_cat)

,response,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,100
0,0.709745,5.169284,-0.801270,-2.481015,0.971358,-2.788133,0.344792,1.319404,-0.229033,0.081958,...,2.221755,0.362435,3.732676,8.089617,3.531047,0.764803,2.611196,1.246202,0.757259,-0.580157
1,-1.182419,5.284342,-1.212539,-2.450351,0.112518,-2.789658,-0.000746,1.257714,-0.020188,0.398173,...,2.329076,0.181900,3.557077,7.937169,3.963873,0.560995,3.143621,0.459065,0.474184,0.468246
2,-0.228918,4.907341,-0.414235,-2.101820,0.583732,-2.926481,-0.648327,1.244020,0.199479,-0.141364,...,1.995018,0.327048,3.774364,7.887075,3.569852,0.890454,3.122125,1.602968,0.943994,0.155247
3,1.070476,5.107220,-0.817031,-2.198386,0.625852,-2.690079,0.150866,1.598720,-0.374176,0.291748,...,1.757760,-0.269355,3.792042,7.879154,3.561271,0.804493,2.588445,1.728053,0.672215,0.121342
4,1.651615,5.420199,-0.525324,-2.415237,1.005190,-2.703323,0.359519,1.376945,0.328053,0.001085,...,2.392239,0.484386,3.667260,7.707040,3.810620,0.830379,2.577513,2.124940,0.033020,-0.599305
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,-1.366329,4.648824,-1.115133,-1.694486,0.818466,-2.517248,-0.381121,1.196717,-0.147013,-0.087889,...,2.135680,0.390318,3.562221,8.027991,4.026159,0.860800,2.668003,1.384969,0.098826,-0.000922
96,1.656332,4.908522,-0.665053,-2.556943,1.114199,-2.873339,-0.223156,1.090769,-0.148751,0.020906,...,1.808230,0.116378,3.532256,7.836456,2.997895,0.751951,3.036141,1.811638,0.358069,-0.718323
97,-1.369651,5.272862,-0.964620,-2.454992,0.439067,-2.718708,0.121382,1.243454,-0.450078,0.218211,...,1.881787,0.284764,3.402504,8.196195,3.283347,0.932596,1.937744,2.838580,0.227059,0.012674
98,-2.335436,4.873174,-0.603693,-2.588740,1.455388,-2.742686,-0.014913,1.362023,-0.303832,-0.016839,...,2.390619,0.499916,3.473040,7.711473,3.276284,0.588535,2.456534,2.181392,0.322333,-0.209638
99,0.638601,5.480088,-0.768131,-2.411605,0.637302,-2.594091,0.353499,1.747251,0.414295,0.074325,...,2.144975,0.486810,3.653917,7.674099,3.764090,1.033709,2.854474,2.115283,0.480203,0.379499

,response,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,100
0,-0.858714,-1.192076,-1.843203,0.425764,-1.928103,-1.706470,-1.907344,-0.806375,0.495380,1.682625,...,-2.556583,-3.999983,3.021161,-1.491902,0.324629,0.579581,5.232790,-0.732302,1.987773,0.182961
1,-1.645498,-1.512046,-2.776914,0.203048,-2.334490,-0.628611,-1.698098,-0.291700,0.348396,1.779148,...,-2.455964,-3.637511,3.189133,-1.108604,0.240107,0.865531,5.464467,-1.311782,2.233184,0.187684
2,-1.271160,-1.505261,-1.766538,0.226851,-2.228543,-1.929425,-1.747420,-0.874122,-0.169380,1.810226,...,-2.647056,-3.873737,3.043445,-2.108507,0.325211,0.569156,5.088865,-0.901268,2.300370,0.468906
3,-0.809590,-2.067170,-2.092256,0.616910,-1.157147,-2.378855,-2.055474,-0.459659,0.218658,1.716537,...,-2.220061,-4.111322,2.946146,-2.630426,0.371037,0.862062,5.085696,-0.843187,1.523889,-0.044226
4,-0.849828,-1.472328,-2.587047,0.889882,-2.803023,-2.060670,-2.031925,-0.535059,-0.239085,2.047370,...,-2.291321,-3.718342,2.865583,-2.399674,0.382917,1.173630,4.889107,-1.197509,3.521448,0.433665
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,-1.697780,-2.395958,-2.248412,-0.660183,-2.038939,-1.708342,-2.055360,-1.592534,0.134013,1.994029,...,-2.371866,-3.617409,3.010403,-1.831470,0.381820,1.280596,4.928786,-1.350042,2.632904,0.277015
76,-1.785944,-1.871045,-2.701426,1.123326,-2.336776,-1.613714,-1.992757,-0.685850,0.389006,1.699597,...,-2.340122,-3.588028,2.845644,-1.893834,0.478603,0.960739,5.312729,-0.808141,2.371492,0.095164
77,-2.363927,-1.785866,-2.459270,0.576606,-2.458442,-0.826019,-1.967408,-0.447435,0.440372,1.143935,...,-2.427535,-3.831840,2.952946,-2.144902,0.192362,0.732021,5.091913,-1.148301,1.466302,-0.043536
78,-0.996614,-1.090444,-2.231536,0.246113,-2.088365,-2.217954,-2.030591,-1.158286,0.147960,1.839563,...,-2.278157,-3.537164,3.366052,-2.380252,0.332666,0.752533,5.321324,-1.130233,0.531972,0.187986
79,-0.888477,-2.837271,-2.104644,0.501004,-2.083480,-2.145835,-2.238674,-0.893656,0.626155,2.215670,...,-2.320195,-4.016915,3.014101,-2.292362,0.010647,2.114517,4.899264,-1.236225,2.042150,-0.236377

,response,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,100
0,2,-1.310469,5.570844,3.700625,-0.619772,0.074271,-0.052646,2.823216,-1.799269,-1.579035,...,4.819066,2.040486,1.986293,5.142695,2.295965,1.155776,4.512663,1.416116,-0.030854,-0.822960
1,1,-1.082107,5.268589,3.426564,-0.592814,0.350732,-0.351167,2.793405,-2.393324,-2.054333,...,4.621089,1.925801,2.339705,4.911947,1.461830,0.858679,4.565820,-0.260662,0.451128,-1.013903
2,2,-0.737008,4.890618,3.495831,-0.810039,0.442562,0.252116,3.102539,-2.453232,-1.890366,...,4.806363,2.068896,2.118783,5.155596,1.162680,1.053035,4.109277,0.480822,-0.241338,-1.097282
3,3,-0.819201,5.091639,3.335201,-0.370575,0.516678,0.110038,2.570169,-2.343234,-1.892962,...,4.399806,2.357678,1.840806,5.226303,1.465903,0.937009,4.079520,0.539711,0.158438,-1.081640
4,2,-0.763279,5.557201,3.330069,-0.635902,0.447687,-0.312029,2.790430,-2.356448,-2.818449,...,4.869561,2.199476,2.026253,5.023058,1.372399,1.235917,3.950441,1.128289,0.020330,-1.223108
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,2,-0.809713,4.917303,3.364738,-0.882983,0.035671,0.254065,2.800092,-2.212543,-1.895990,...,4.616638,2.356582,1.966760,4.541395,1.447753,0.797124,4.966511,1.640023,0.123759,-0.969684
101,1,-1.024245,5.097656,3.526080,-0.764799,0.614209,0.268911,2.683918,-1.644659,-1.821519,...,4.894150,2.121815,1.740149,5.060649,1.266335,0.937450,4.609844,0.894055,0.065500,-1.151515
102,3,-1.347499,5.217781,3.363037,-0.596614,1.114721,0.148757,2.703218,-2.633046,-1.557009,...,4.903644,2.212217,2.525541,4.960240,1.529156,0.882572,4.154050,0.454436,0.470143,-0.949239
103,1,-1.096823,5.758413,3.526562,-0.592390,0.658155,-0.082963,2.911165,-2.557210,-2.153025,...,4.867976,2.417201,1.925608,5.263617,1.555666,1.300913,4.239458,1.716188,-0.174082,-1.232906
104,2,-1.050452,5.227704,3.572933,-0.507850,0.785874,-0.163091,2.841950,-2.353404,-1.734339,...,4.448237,2.318687,2.739278,5.465868,1.597587,1.558405,4.900981,0.372170,-0.393087,-1.121588

,response,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,100
0,3,4.769045,2.543019,0.127175,0.915306,-1.533501,-1.506954,-2.092641,4.831195,-0.895564,...,0.457183,0.697152,0.985471,1.314532,3.874959,3.954645,-3.308962,1.215349,0.258778,0.909181
1,3,5.018501,2.510326,-0.354174,0.836314,-1.441408,-1.279166,-1.952684,5.115174,-1.016085,...,1.324583,0.500394,-0.396992,1.542943,4.067113,3.846578,-3.243592,1.389933,0.547100,0.846260
2,3,4.777021,2.444106,-0.211616,1.276217,-1.884173,-0.344954,-2.020747,4.534157,-0.914388,...,0.544318,0.374025,-0.882429,1.180283,3.777334,3.706993,-3.269312,1.164933,-0.458075,0.917365
3,2,4.670300,2.133287,0.160373,1.018033,-1.668420,-0.655789,-1.918660,3.901115,-0.751446,...,0.682099,0.728456,-1.550653,1.217963,4.566282,3.768361,-3.272327,1.315975,0.305532,0.686334
4,1,4.175020,2.321022,0.232931,1.254426,-1.740281,-0.941282,-3.815338,4.018373,-1.745579,...,1.240334,-0.032016,-1.387028,1.636593,4.332934,3.911513,-3.142013,1.607726,0.055178,0.651507
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,2,4.501208,2.509107,0.109379,1.711110,-1.612816,-1.401761,-1.423005,4.660238,-1.100626,...,0.516574,0.951326,-0.208152,1.669521,4.252707,3.810440,-3.237650,0.915388,0.450955,0.818702
76,2,4.159895,2.595269,-0.506128,1.452436,-1.739688,-0.565483,-2.124122,4.580203,-1.332073,...,0.415372,-0.087372,-1.714914,1.437499,3.435024,3.916532,-3.204420,2.143436,0.346091,0.781715
77,1,4.551205,2.288389,-0.851173,1.616766,-1.835022,-1.072017,-1.560335,4.247898,-0.711451,...,0.107727,0.438576,-1.295839,1.480109,4.274559,3.632350,-3.172828,1.194807,0.006112,0.566536
78,3,3.860609,2.431069,-0.359509,1.211128,-1.751888,-1.669110,-1.111645,4.870790,-1.192881,...,0.035782,1.325843,-0.384502,1.516608,4.106231,3.820769,-3.155858,0.919099,0.523355,0.861473
79,3,4.569016,2.406346,-0.419975,0.701233,-1.851113,-1.111626,-3.385429,4.554030,-1.060488,...,0.197951,0.430888,-2.771304,1.160451,4.058868,3.833038,-3.126279,1.183269,0.798316,0.856264

Then we can split the target data into train and test sets.

In [6]:
from sklearn.model_selection import train_test_split

target_synth_train_comb_cont, target_synth_test_cont = train_test_split(
    target_synth_data_cont,
    train_size = num_samples_target + samples_target_ensemble,
    test_size = samples_target_test
)

target_synth_train_comb_cat, target_synth_test_cat = train_test_split(
    target_synth_data_cat,
    train_size = num_samples_target + samples_target_ensemble,
    test_size = samples_target_test
)

target_synth_train_cont, target_synth_train_ensemble_cont = train_test_split(
    target_synth_train_comb_cont,
    train_size = num_samples_target,
    test_size = samples_target_ensemble
)

target_synth_train_cat, target_synth_train_ensemble_cat = train_test_split(
    target_synth_train_comb_cat,
    train_size = num_samples_target,
    test_size = samples_target_ensemble
)

The data is now ready to be used for transfer learning.

We provide a DatasetContainer helper class to keep the different datasets organized. Optionally, id_tuple can also be set which is used to label the scenario and replicate IDs if performing large scale simulation studies. These IDs are passed to the output after model fitting.

In [7]:
from omicstl.simulation_utils.data_utils import DatasetContainer
datasets_cont = DatasetContainer(
	source_data=source_synth_data_cont,
	target_data=target_synth_train_cont,
    target_ensemble_data=target_synth_train_ensemble_cont,
	target_test_data=[target_synth_test_cont]
)
datasets_cont.set_response_column("response") # Identify response column

datasets_cat = DatasetContainer(
	source_data=source_synth_data_cat,
	target_data=target_synth_train_cat,
    target_ensemble_data=target_synth_train_ensemble_cat,
	target_test_data=[target_synth_test_cat]
)
datasets_cat.set_response_column("response") # Identify response column

We enable automatic tuning over a parameter grid for both deep learning models:

In [8]:
param_grid = {
	"dropout": [0.25, 0.5],
	"n_latent_dims": [2],
	"hidden_dim_base": [6],
	"lr": [0.01, 0.001],
	"source_epochs": [1000],
	"target_epochs": [1000],
	"freeze": ["none"],
	"weight_decay": [1e-4, 1e-2],
	"gamma": [1, 2, 3]
}

Deep learning models can be fit using a DatasetContainer and parameter grid using fit_dl_model, which returns a dataframe with results, the trained transfer learning model, and the model trained on only the target dataset.

In [ ]:
import torch
from torch import device
import random
from omicstl.simulation_utils.model_utils import fit_dl_model

random.seed(42)
torch.manual_seed(42)
out, model, model_targetonly = fit_dl_model(
	datasets_cont,
	"mult_vae",
	device("cpu"),
	param_grid
)
display(out)

random.seed(42)
torch.manual_seed(42)
out, model, model_targetonly = fit_dl_model(
	datasets_cat,
	"mult_vae",
	device("cpu"),
	param_grid
)
display(out)

/opt/venv/lib/python3.12/site-packages/omicstl/simulation_utils/model_utils.py:959: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, test_results], ignore_index=True)

,scenario,replicate,split,model,model_type,model_id,rmse,mae,acc,f1,...,dropout,hidden_dim_base,n_latent_dims,source_epochs,target_epochs,freeze,z_dim_base,lr,weight_decay,gamma
0,None,None,test_0,mult_vae,mult_vae,target,0.747677,0.609028,NaN,NaN,...,0.5,6.0,2.0,1000.0,1000.0,none,12.0,0.01,0.0001,2.0
1,None,None,test_0,mult_vae,mult_vae,target_nosource,0.745388,0.581269,NaN,NaN,...,0.5,6.0,2.0,1000.0,1000.0,none,12.0,0.01,0.0001,2.0

/opt/venv/lib/python3.12/site-packages/omicstl/simulation_utils/model_utils.py:959: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, test_results], ignore_index=True)

,scenario,replicate,split,model,model_type,model_id,rmse,mae,acc,f1,...,dropout,hidden_dim_base,n_latent_dims,source_epochs,target_epochs,freeze,z_dim_base,lr,weight_decay,gamma
0,None,None,test_0,mult_vae,mult_vae,target,NaN,NaN,0.44,0.428767,...,0.25,6.0,2.0,1000.0,1000.0,none,12.0,0.01,0.0100,2.0
1,None,None,test_0,mult_vae,mult_vae,target_nosource,NaN,NaN,0.28,0.229459,...,0.25,6.0,2.0,1000.0,1000.0,none,12.0,0.01,0.0001,3.0

In [10]:
random.seed(42)
torch.manual_seed(42)
out, model, model_targetonly = fit_dl_model(
	datasets_cont,
	"mult_mlp",
	device("cpu"),
	param_grid
)
display(out)

random.seed(42)
torch.manual_seed(42)
out, model, model_targetonly = fit_dl_model(
	datasets_cat,
	"mult_mlp",
	device("cpu"),
	param_grid
)
display(out)

/opt/venv/lib/python3.12/site-packages/omicstl/simulation_utils/model_utils.py:959: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, test_results], ignore_index=True)

,scenario,replicate,split,model,model_type,model_id,rmse,mae,acc,f1,...,dropout,hidden_dim_base,n_latent_dims,source_epochs,target_epochs,freeze,z_dim_base,lr,weight_decay,gamma
0,None,None,test_0,mult_mlp,mult_mlp,target,0.607661,0.474682,NaN,NaN,...,0.5,6.0,2.0,1000.0,1000.0,none,12.0,0.001,0.01,3.0
1,None,None,test_0,mult_mlp,mult_mlp,target_nosource,0.799034,0.605407,NaN,NaN,...,0.5,6.0,2.0,1000.0,1000.0,none,12.0,0.010,0.01,2.0

/opt/venv/lib/python3.12/site-packages/omicstl/simulation_utils/model_utils.py:959: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, test_results], ignore_index=True)

,scenario,replicate,split,model,model_type,model_id,rmse,mae,acc,f1,...,dropout,hidden_dim_base,n_latent_dims,source_epochs,target_epochs,freeze,z_dim_base,lr,weight_decay,gamma
0,None,None,test_0,mult_mlp,mult_mlp,target,NaN,NaN,0.36,0.346374,...,0.25,6.0,2.0,1000.0,1000.0,none,12.0,0.001,0.0100,3.0
1,None,None,test_0,mult_mlp,mult_mlp,target_nosource,NaN,NaN,0.32,0.320000,...,0.25,6.0,2.0,1000.0,1000.0,none,12.0,0.010,0.0001,1.0

The random forest based models can also be fit using a python interface to the R modeling code.

In [ ]:
from omicstl.r_utils import set_seed
from omicstl.simulation_utils.model_utils import fit_rf_model

random.seed(42)
out, model = fit_rf_model(datasets_cont)
display(out)

random.seed(42)
set_seed(42)
out, model = fit_rf_model(datasets_cat)
display(out)

/opt/venv/lib/python3.12/site-packages/omicstl/simulation_utils/model_utils.py:1101: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, pd.DataFrame([test_row])], ignore_index=True)

,scenario,replicate,split,model,model_type,model_id,rmse,mae,acc,f1,mcc,precision,recall
0,None,None,test_0,rf,pred_source,target,3.587705,3.544497,NaN,NaN,NaN,NaN,NaN
1,None,None,test_0,rf,pred_0,target,0.587408,0.451815,NaN,NaN,NaN,NaN,NaN
2,None,None,test_0,rf,pred_1,target,0.584787,0.433747,NaN,NaN,NaN,NaN,NaN
3,None,None,test_0,rf,pred_2,target,0.594194,0.448339,NaN,NaN,NaN,NaN,NaN
4,None,None,test_0,rf,pred_3,target,0.557831,0.429201,NaN,NaN,NaN,NaN,NaN
5,None,None,test_0,rf,pred_ensemble,target,0.574551,0.428616,NaN,NaN,NaN,NaN,NaN

/opt/venv/lib/python3.12/site-packages/omicstl/simulation_utils/model_utils.py:1101: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, pd.DataFrame([test_row])], ignore_index=True)

,scenario,replicate,split,model,model_type,model_id,rmse,mae,acc,f1,mcc,precision,recall
0,None,None,test_0,rf,truth,target,NaN,NaN,0.00,0.000000,NaN,0.000000,0.00
1,None,None,test_0,rf,pred_source,target,NaN,NaN,0.32,0.155152,NaN,0.102400,0.32
2,None,None,test_0,rf,pred_0,target,NaN,NaN,0.44,0.439320,NaN,0.444429,0.44
3,None,None,test_0,rf,pred_1,target,NaN,NaN,0.56,0.468900,NaN,0.412000,0.56
4,None,None,test_0,rf,pred_2,target,NaN,NaN,0.44,0.429333,NaN,0.424935,0.44
5,None,None,test_0,rf,pred_3,target,NaN,NaN,0.36,0.357222,NaN,0.362286,0.36
6,None,None,test_0,rf,pred_ensemble,target,NaN,NaN,0.56,0.453333,NaN,0.382308,0.56

Advanced users can also work directly with the base classes we provide for each TL model via TransferForest() and MultiViewModel().